### ISSUE TITLE
Popup clarity

### ISSUE THREAD

**Issue by RenatoGeh** [MarvellousSoft/MarvInc#131]
For popups that represent your own thoughts, set a permanent color.
For popups that are actually someone else replying to you, add a signature and different color.

**Comment by rilifon** [comment]
color in the text? on a border? what do you guys suggest?

**Comment by rilifon** [comment]
there are lots of puzzles that I don't know if there should be a signature or not. Can you guys @RenatoGeh & @yancouto go through all popups you guys wrote and add a signature when needed? I will do the ones I made

**Comment by yancouto** [comment]
All Liv and Fergus popups now have signatures.

**Comment by rilifon** [comment]
I corrected all popups for consistency. Mainly adding spaces on popups buttons and making them start in lower case (except when necessary), and for popups that represent your own thoughts I made them all in third person. Only thing left to close this issue is to make something different for those "inner thought popups". My suggestions is just making them in a lighter or grayer text color.

**Comment by rilifon** [comment]
@yancouto @RenatoGeh thoughts on this? Should we add stylize text to popups to create a new effect for "inner thoughts popups"?
