### ISSUE TITLE
[Esthetics] Head antenna (?) nondistinguishable. Head gruesome.

### ISSUE THREAD

**Issue by Houkime** [MarvellousSoft/MarvInc#182]
Head antenna makes back of the head look like a gruesome swollen bulb instead of being a distinct antenna in most cases.

Here you can distinguish antenna on the right, but it is just a halfhead swollen bulb on the left.
![image](https://user-images.githubusercontent.com/32805122/34697500-493ce0ae-f4cb-11e7-9b15-15287c306752.png)

I might be terribly wrong about my interpretation of this pixelart but this just highlights the problem of a high visual ambiguity.

**Comment by RenatoGeh** [comment]
@rilifon

**Comment by rilifon** [comment]
Hey there houkime! The way we generate robots is: we get a random iamge for the body (but there is only one for now) and a random image for the head (again, there is only one =P). However, the images of bodies and heads are black and white, and we colorize them using the framework. Since the head has both the face and the hair (the antenna you are referencing is part of the hair outline hahah), when we color the head, both of them stay the same color. And its jsut weird haha.

We are planning a polish release soon, and I will fix this by separating the hair sprite from the face, so we can color each one individually. I think this will improve the bots visually.

Thanks for the issue!
