### ISSUE TITLE
[unintuitive??] right/left ambiguity

### ISSUE THREAD

**Issue by Houkime** [MarvellousSoft/MarvInc#186]
Well, it's part of my own mistake, but I managed to go up to CS1 status sincerely thinking that there are two direction systems in the game:

1. east/west/north/south for absolute directions
2. (empty for forward)/right/left for relative directions with "back" omitted for some reasons.
And when I tried to use the fact of point symmetry in B.4 to reduce code size bot blew up cause he couldn't pickup a bucket on HIS right.

![image](https://user-images.githubusercontent.com/32805122/34900194-bb9b1e7c-f7f5-11e7-9298-ad2accc12f60.png)

And only then I understood that left/right are part of left/right/up/down, which is functionally  identical to east/west/north/south (which are unambigously absolute and thereby preferred) and thereby not entirely clear why existing at all.
(To create ambiguity? :smile: )

Some separated note on direction system in the manual would be nice.
And an actual system for relative directions would also be nice. Penalty in terms of code lines/ticks for directional relativity usage via "turn" is kinda high. Not sure if it's reasonable really to penalise relativity so much especially considering that working with relativity is inherently harder.

**Comment by yancouto** [comment]
Hi @Houkime, thanks for the contribution :D

I added left/right/up/down because I find west/east more confusing than left/right (for some reason, I always have to convert them in my head). I see that east/west/north/south sound more absolute. We will surely add a note on the manual, and possibly explain it better in an email.

I agree that using `turn clock` for relative directions is kind of a bummer. We thought of implementing something like you said, but never got around to it for some reason.

@RenatoGeh @rilifon, what do you think about adding relative directions now?

Some topics:
1. Is left/right/front/back the best way or is there a possible different naming that sounds more unambiguously relative? counterclockwise/clockwise/front/back? counter/clock/front/back?
1. How will it affect all the puzzles we already have?

I think some puzzles will be possible to solve with just a few less lines, but much less hassle. Also it is very easy to implement.
