### ISSUE TITLE
Windows: Logging in with existing name but changed upper/lowercase letters will overwrite save data

### ISSUE THREAD

**Issue by Ingix** [MarvellousSoft/MarvInc#193]
This is a (slightly edited) repost from an issue I posted on itch.io, but it makes sense to have to here as well:

Using version 1.1.1 on Windows, not sure if the problem still exists with 1.1.2:

I'm playing as user name "Abc". After many days, I logged in hastily as "abc". I was greeted as a new employee. OK, I thought, the game differentiates between small/capital letters. So I closed the game, opened it again and logged in as "Abc". But again I was greeted as a new employee, with the same employee number as with "abc". If I did not have had a backup of the data from the day before, I would have had to restart now (many hours played).

The reason seems to be that the game internally differentiates between "Abc" and "abc", but Windows does not (when considering filenames). So when the game tries to create a save directory for the new user "abc", it will be the same directory as for "Abc", overwriting the progress of "Abc".

I understand that this diffferent in unixoid architctures. Maybe it would be feasable to test if the supposedly new save directory already exists, and warn the user in that case.

**Comment by rilifon** [comment]
Fix this issue.

Our solution: We now force lowercase on creating and accesing usernames. This will prevent future conflicts with Windows or other OS that doesn't differentiate cases.
We couldn't find a reasonable way to rename the usernames ourself, since this is also OS dependent to write the new path, but we throw a warning popup in the user face requesting him to manually rename the save folder, in case he has any username with uppercase letters and wants to keep his old save-file

Thanks again for the bug report @Ingix !
