### ISSUE TITLE
Love 11.2 support

### ISSUE THREAD

**Issue by dulsi** [MarvellousSoft/MarvInc#264]
I tried running Marvellous Inc with Love 11.2 but text box for user name didn't display. Coding area also didn't seem to work.

**Comment by yancouto** [comment]
We don't plan to support love 11 or newer versions.

**Comment by dulsi** [comment]
I assume you don't want a pull request with the fixes then. If you are interested I've done some quick fixes in my fork. Scroll bar doesn't seem to draw yet. Not sure what other bugs exist but I can now get into the game.

**Comment by yancouto** [comment]
The love versions are incompatible, so we'd rather stay with the version that we started. Migrating would surely bring some small problems (and we'd have to change stuff in the deployment as well), so I do not think it is worth it, since this isn't being actively worked on anymore.
If you can't run the game properly, you can use one of our packaged releases, it already has love built-in so there shouldn't be a problem in running them.
