### ISSUE TITLE
Login (menu) screen with multiple saves

### ISSUE THREAD

**Issue by rilifon** [MarvellousSoft/MarvInc#27]
- [ ] Support multiple saves (depends on #25).
- [x] Create system for creating a new user (save).
- [ ] Create a button box in the menu screen for each save found that can load that save.

**Comment by rilifon** [comment]
@yancouto 
Does it work on the web version? Does love.js have some api to work with cookies?

If not, can you create an issue for creating saves on the web version?

**Comment by yancouto** [comment]
I put up an updated web version [here](https://linux.ime.usp.br/~yancouto/stuff/marvellous_dev/). I get a javascript error the second time I run it, probably because of the saves.

We can investigate if the javascript error is simple and our fault, but if it just doesn't work on love.js then there is no way of fixing it.
