### ISSUE TITLE
Store information for completed puzzles

### ISSUE THREAD

**Issue by rilifon** [MarvellousSoft/MarvInc#30]
Store information such as # of lines used or # steps needed to completion

**Comment by rilifon** [comment]
@yancouto maybe you can integrate this with the save system since we are already saving the puzzles?

**Comment by yancouto** [comment]
We should only add this if we're gonna use it somewhere

**Comment by rilifon** [comment]
The only reasons I could think is for achievements (e.g. completed the puzzle X in 6 lines);
 maybe some hidden or optional challenges (you receive an email from a misterious source telling you to complete old puzzles in X lines or steps, and if you comply with the challenges you get extra hard puzzles or a different ending);
Or maaaaybe just to compare between friends who was more efficient in each puzzle (zachlikes usually have this feature but personally I just ignore it haha)

**Comment by Houkime** [comment]
You actually can use a t-i-i-iny little bit of Github server powers to make it awesome i think.

Thing is you can just store here somewhere a file (or have a public table on a free website like <project>.github.io) that stores worldwide player stats (if they want to submit) on each puzzle. Every time game is launched it syncs this tiny little file with the net so you can see a zachstyle graphs on efficiency worldwide for each puzzle. 

The main challenge is to _collect_ playerstats however. 
In the minimalistic scenario game just writes you (dev) a letter with stats (no, there's no potential personal info problem because it is OSS and everybody can see how it works) and you then have a script on your computer that compiles mails into daily leaderboard updates.

Of course it is much easier to do if you have even a tiny little server. (However I don't yet know a free way to have a microserver outside of your own PC-s. Right now I save my family's old machinery including smartphones to repurpose them as microservers in some time.)

**Comment by yancouto** [comment]
Scoreboards would be really cool to have.

They would be difficult to implement though, figuring out how to collect, store and show the data. I think we should only do this if we have a reasonable number of players.

**Comment by rilifon** [comment]
Bump since this is more relevant now

**Comment by rilifon** [comment]
Closing since we actually have scoreboards now
